version: "3.7"
services:
  php:
    build: ./.docker/php/
    volumes:
      - ./:/var/www/html/
    ports:
      - 7010:80
    environment:
      IDP_ENVIRONMENT: docker

  mysql:
    image: mysql:5.7
    volumes:
        - mysql:/var/lib/mysql
        - ./data:/docker-entrypoint-initdb.d
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: portfolio_u
        MYSQL_PASSWORD: p0rtf0li0_p!!
        MYSQL_DATABASE: db_portfolio_u

  phpmyadmin:
    depends_on:
        - mysql
    image: phpmyadmin/phpmyadmin
    ports:
        - 7011:80
    environment:
        PMA_HOSTS: mysql
        PMA_USER: portfolio_u
        PMA_PASSWORD: p0rtf0li0_p!!
  email:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
volumes:
  mysql:
